### ISSUE TITLE
feat: add require to check balance

### ISSUE THREAD

**Issue by fosgate29** [genesisdotre/trustless-token-transfer-trade#1]
https://github.com/genesisdotre/trustless-token-transfer-trade/blob/3cd68a1231ae5508c120cf309470289aff82a627/contracts/TrustlessTokenTransfer.sol#L60

Add a require to check if balance is zero. If it is zero, no need to keep on. Fail fast and hard

**Comment by marsrobertson** [comment]
Now it became `selfDestruct`

https://github.com/genesisdotre/trustless-token-transfer-trade/blob/7fe75fb03acfac7e3b15d8fdcb160cded012b0c5/contracts/TrustlessTokenTransfer.sol#L65

Thanks for the comments!
